version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27018:27017/tcp
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      retries: 3
      interval: 5s
      timeout: 5s
      start_period: 5s
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081/tcp
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  api:
    build: .
    ports:
      - "9000:9000"




